### DISCUSSION TITLE
Homeassistant with SignalK on BBN OS

### DISCUSSION THREAD

**Discussion by mgrouch** [bareboat-necessities/lysmarine_gen#302] [General]
Here is how you can integrate 
Homeassistant with SignalK on your boat 
on BBN OS

https://github.com/bareboat-necessities/my-bareboat/blob/master/docs/bareboat-os.adoc#1451-homeassistant-with-signalk

BBN OS comes with Homeassistant included. You just need to activate it following Getting Started Guide. 

> Enable "Signal K - MQTT Home Assistant Bridge" plugin in SignalK (with run local server option, port 2883)

> In Home assistant add MQTT integration Broker: lysmarine Port: 2883 Subscribe Topic:

`+/+/#`

> Edit 

/home/homeassistant/.homeassistant/configuration.yaml

```
mqtt: # SignalK MQTT HA Bridge
  # https://developers.home-assistant.io/docs/core/entity/sensor/
  sensor:
    - name: "Wind App Speed"
      unique_id: "speedApparent"
      #device_class: "wind_speed"
      state_topic: "vessels/self/environment/wind/speedApparent"
      unit_of_measurement: "kn"
      value_template: "{{ value_json * 1.9438452 }}"

    - name: "Wind App Angle"
      unique_id: "angleApparent"
      state_topic: "vessels/self/environment/wind/angleApparent"
      unit_of_measurement: "deg"
      value_template: "{{ value_json * 180 / 3.14159265359 }}"
```

> Edit Dashboard, Click "Add Card" and you can select to draw gauges, meters, chart, etc views for your sensors
